import { Wilaya } from '../types';

export const ALGERIAN_WILAYAS: Wilaya[] = [
  { num: 1, nameAr: "أدرار", nameFr: "Adrar", shippingHome: 1100, shippingDesk: 750, available: true },
  { num: 2, nameAr: "الشلف", nameFr: "Chlef", shippingHome: 700, shippingDesk: 400, available: true },
  { num: 3, nameAr: "الأغواط", nameFr: "Laghouat", shippingHome: 900, shippingDesk: 550, available: true },
  { num: 4, nameAr: "أم البواقي", nameFr: "Oum El Bouaghi", shippingHome: 800, shippingDesk: 450, available: true },
  { num: 5, nameAr: "باتنة", nameFr: "Batna", shippingHome: 800, shippingDesk: 450, available: true },
  { num: 6, nameAr: "بجاية", nameFr: "Béjaïa", shippingHome: 700, shippingDesk: 450, available: true },
  { num: 7, nameAr: "بسكرة", nameFr: "Biskra", shippingHome: 900, shippingDesk: 550, available: true },
  { num: 8, nameAr: "بشار", nameFr: "Béchar", shippingHome: 1100, shippingDesk: 700, available: true },
  { num: 9, nameAr: "البليدة", nameFr: "Blida", shippingHome: 500, shippingDesk: 350, available: true },
  { num: 10, nameAr: "البويرة", nameFr: "Bouira", shippingHome: 650, shippingDesk: 450, available: true },
  { num: 11, nameAr: "تمنراست", nameFr: "Tamanrasset", shippingHome: 1500, shippingDesk: 1100, available: true },
  { num: 12, nameAr: "تبسة", nameFr: "Tébessa", shippingHome: 800, shippingDesk: 500, available: true },
  { num: 13, nameAr: "تلمسان", nameFr: "Tlemcen", shippingHome: 800, shippingDesk: 450, available: true },
  { num: 14, nameAr: "تيارت", nameFr: "Tiaret", shippingHome: 800, shippingDesk: 450, available: true },
  { num: 15, nameAr: "تيزي وزو", nameFr: "Tizi Ouzou", shippingHome: 650, shippingDesk: 400, available: true },
  { num: 16, nameAr: "الجزائر", nameFr: "Alger", shippingHome: 400, shippingDesk: 300, available: true },
  { num: 17, nameAr: "الجلفة", nameFr: "Djelfa", shippingHome: 900, shippingDesk: 550, available: true },
  { num: 18, nameAr: "جيجل", nameFr: "Jijel", shippingHome: 700, shippingDesk: 450, available: true },
  { num: 19, nameAr: "سطيف", nameFr: "Sétif", shippingHome: 700, shippingDesk: 450, available: true },
  { num: 20, nameAr: "سعيدة", nameFr: "Saïda", shippingHome: 800, shippingDesk: 450, available: true },
  { num: 21, nameAr: "سكيكدة", nameFr: "Skikda", shippingHome: 700, shippingDesk: 450, available: true },
  { num: 22, nameAr: "سيدي بلعباس", nameFr: "Sidi Bel Abbès", shippingHome: 700, shippingDesk: 450, available: true },
  { num: 23, nameAr: "عنابة", nameFr: "Annaba", shippingHome: 700, shippingDesk: 450, available: true },
  { num: 24, nameAr: "قالمة", nameFr: "Guelma", shippingHome: 800, shippingDesk: 450, available: true },
  { num: 25, nameAr: "قسنطينة", nameFr: "Constantine", shippingHome: 700, shippingDesk: 450, available: true },
  { num: 26, nameAr: "المدية", nameFr: "Médéa", shippingHome: 650, shippingDesk: 450, available: true },
  { num: 27, nameAr: "مستغانم", nameFr: "Mostaganem", shippingHome: 700, shippingDesk: 450, available: true },
  { num: 28, nameAr: "المسيلة", nameFr: "M'Sila", shippingHome: 800, shippingDesk: 500, available: true },
  { num: 29, nameAr: "معسكر", nameFr: "Mascara", shippingHome: 700, shippingDesk: 450, available: true },
  { num: 30, nameAr: "ورقلة", nameFr: "Ouargla", shippingHome: 1000, shippingDesk: 600, available: true },
  { num: 31, nameAr: "وهران", nameFr: "Oran", shippingHome: 700, shippingDesk: 400, available: true },
  { num: 32, nameAr: "البيض", nameFr: "El Bayadh", shippingHome: 1000, shippingDesk: 700, available: true },
  { num: 33, nameAr: "إليزي", nameFr: "Illizi", shippingHome: 1500, shippingDesk: 1050, available: true },
  { num: 34, nameAr: "برج بوعريريج", nameFr: "Bordj Bou Arréridj", shippingHome: 700, shippingDesk: 450, available: true },
  { num: 35, nameAr: "بومرداس", nameFr: "Boumerdès", shippingHome: 600, shippingDesk: 350, available: true },
  { num: 36, nameAr: "الطارف", nameFr: "El Tarf", shippingHome: 800, shippingDesk: 450, available: true },
  { num: 37, nameAr: "تندوف", nameFr: "Tindouf", shippingHome: 1300, shippingDesk: 750, available: true },
  { num: 38, nameAr: "تيسمسيلت", nameFr: "Tissemsilt", shippingHome: 800, shippingDesk: 450, available: true },
  { num: 39, nameAr: "الوادي", nameFr: "El Oued", shippingHome: 900, shippingDesk: 550, available: true },
  { num: 40, nameAr: "خنشلة", nameFr: "Khenchela", shippingHome: 800, shippingDesk: 500, available: true },
  { num: 41, nameAr: "سوق أهراس", nameFr: "Souk Ahras", shippingHome: 800, shippingDesk: 500, available: true },
  { num: 42, nameAr: "تيبازة", nameFr: "Tipaza", shippingHome: 600, shippingDesk: 350, available: true },
  { num: 43, nameAr: "ميلة", nameFr: "Mila", shippingHome: 700, shippingDesk: 450, available: true },
  { num: 44, nameAr: "عين الدفلى", nameFr: "Aïn Defla", shippingHome: 700, shippingDesk: 450, available: true },
  { num: 45, nameAr: "النعامة", nameFr: "Naâma", shippingHome: 1000, shippingDesk: 600, available: true },
  { num: 46, nameAr: "عين تموشنت", nameFr: "Aïn Témouchent", shippingHome: 700, shippingDesk: 450, available: true },
  { num: 47, nameAr: "غرداية", nameFr: "Ghardaïa", shippingHome: 1000, shippingDesk: 550, available: true },
  { num: 48, nameAr: "غليزان", nameFr: "Relizane", shippingHome: 700, shippingDesk: 450, available: true },
  { num: 49, nameAr: "تيميمون", nameFr: "Timimoun", shippingHome: 1300, shippingDesk: 750, available: true },
  { num: 50, nameAr: "برج باجي مختار", nameFr: "Bordj Baji Mokhtar", shippingHome: 1500, shippingDesk: 1000, available: true },
  { num: 51, nameAr: "أولاد جلال", nameFr: "Ouled Djellal", shippingHome: 900, shippingDesk: 550, available: true },
  { num: 52, nameAr: "بني عباس", nameFr: "Béni Abbès", shippingHome: 1300, shippingDesk: 800, available: true },
  { num: 53, nameAr: "عين صالح", nameFr: "In Salah", shippingHome: 1400, shippingDesk: 950, available: true },
  { num: 54, nameAr: "عين قزام", nameFr: "In Guezzam", shippingHome: 1500, shippingDesk: 1000, available: true },
  { num: 55, nameAr: "تقرت", nameFr: "Touggourt", shippingHome: 950, shippingDesk: 600, available: true },
  { num: 56, nameAr: "جانت", nameFr: "Djanet", shippingHome: 2200, shippingDesk: 1550, available: true },
  { num: 57, nameAr: "المغير", nameFr: "El M'Ghair", shippingHome: 950, shippingDesk: 600, available: true },
  { num: 58, nameAr: "المنيعة", nameFr: "El Meniaa", shippingHome: 1000, shippingDesk: 550, available: true }
];
